### ISSUE TITLE
Request dnsutils package be added as part of the base image. 

### ISSUE THREAD

**Issue by BeldrothTheGold** [sileshn/ManjaroWSL2#12]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22621.1992]

### Kernel Version

Kernel version: 5.15.90.1

### Repro Steps

Attempt to perform a nslookup with base image.

$ nslookup <hostname or IP>

### Expected Behavior

nslookup should be present and perform the needful lookup

### Actual Behavior

The command isn't available in the base MarjaroWSL2 image so you get a command not found error. 
This is part of the dnsutils package.

Having these tools available the ability to download packages in order to diagnose DNS related network issues. This is especially important in WSL in environments where you're connection is routed through a VPN. In this case DNS traffic to "normal" DNS servers may be blocked.

**Comment by sileshn** [comment]
https://github.com/sileshn/ManjaroWSL2/commit/0a09955ba15c7beba950dad43c52b29079cf6a1f
