### ISSUE TITLE
Can not open manjaro this time

### ISSUE THREAD

**Issue by wenwen12345** [sileshn/ManjaroWSL2#2]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22621.819]

### Kernel Version

can not open manjaro

### Repro Steps

use wsl.exe to run manjaro.

### Expected Behavior

灾难性故障
Error code: Wsl/Service/CreateInstance/E_UNEXPECTED

[已退出进程，代码为 4294967295 (0xffffffff)]

### Actual Behavior

manjaro is open

**Comment by sileshn** [comment]
Cannot reproduce. 

https://www.thewindowsclub.com/wsl-process-exited-with-code-4294967295-in-windows-11

https://github.com/microsoft/WSL/issues/5092

**Comment by wenwen12345** [comment]
It doesn't work

**Comment by sileshn** [comment]
Can't help then as I cannot reproduce the issue.

**Comment by wenwen12345** [comment]
At last . I uninstall it and reinstall it.
