### ISSUE TITLE
GPU integration with ManjaroWSL2

### ISSUE THREAD

**Issue by rz1027** [sileshn/ManjaroWSL2#21]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22631.2861]

### Kernel Version

5.15.146.1-microsoft-standard-WSL2 

### Repro Steps

I came into this while using hashcat:
`hashcat -I `
hashcat (v6.2.6) starting in backend information mode

```
clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

ATTENTION! No OpenCL, HIP or CUDA compatible platform found.

You are probably missing the OpenCL, CUDA or HIP runtime installation.

* AMD GPUs on Linux require this driver:
  "AMDGPU" (21.50 or later) and "ROCm" (5.0 or later)
* Intel CPUs require this runtime:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* NVIDIA GPUs require this runtime and/or driver (both):
  "NVIDIA Driver" (440.64 or later)
  "CUDA Toolkit" (9.0 or later)
  
```
  
  
  Despite nvidia-smi finding my 4070 gpu.

Is there a way to apply computation via my host GPU? 
Seems Nvidia supports easy installation for Ubuntu, and hints on installing nvidia-toolkit-12-x alone to handle this on other distros.
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started-with-cuda-on-wsl

### Expected Behavior

It would be nice to be able to run GPU processes on the WSL side, might be beneficial for machine learning or hash cracks...

### Actual Behavior

I can detect the GPU with nvidia-smi, but cant using clinfo, hashcat, or johntheripper.

**Comment by sileshn** [comment]
https://gist.github.com/slavistan/53c8e2627bf9ca202ab6c56ef4d5c497
