### ISSUE TITLE
I can't run Manjaro

### ISSUE THREAD

**Issue by Serega007RU** [sileshn/ManjaroWSL2#3]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.19045.2546]

### Repro Steps

Just run Manjaro.exe

### Expected Behavior

It should start

### Actual Behavior

I get an error:
```
PS D:\PortablePrograms\Manjaro> .\Manjaro.exe
Processing fstab with mount -a failed.

<3>WSL (9) ERROR: CreateProcessEntryCommon:570: execvpe /bin/bash failed 8
<3>WSL (9) ERROR: CreateProcessEntryCommon:579: Create process not expected to return
```

**Comment by Serega007RU** [comment]
Sorry, my jamb, I installed Manjaro of the wrong architecture

**Comment by faelpinho** [comment]
@Serega007RU I got the same error. What do you do to solve it?

**Comment by Serega007RU** [comment]
@faelpinho I tried to install Manjaro with arm64 architecture (I accidentally thought it was x64), that is, you need to install the first option and not the second
![image](https://github.com/user-attachments/assets/3132bfd4-095f-4ed5-94ce-258e1b5d14fb)

**Comment by faelpinho** [comment]
@Serega007RU I installed the right version, but in my case, I just closed and opened again the WSL window, and now it works fine.
Thank you!
