### ISSUE TITLE
Orphan removal causes ManjaroWSL2 Catastrophic failure

### ISSUE THREAD

**Issue by Feat-FeAR** [sileshn/ManjaroWSL2#4]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.19044.2728]

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Repro Steps

1. Use `$ sudo pacman -Rs $(pacman -Qdtq)` to remove orphans, according to Manjaro official Wiki
2. Shutdown and restart

### Expected Behavior

https://wiki.manjaro.org/index.php/Pacman_Overview#Viewing_and_Removing_Orphans

### Actual Behavior

![image](https://user-images.githubusercontent.com/88393554/231831961-a2d00b36-53bb-4005-8e28-00bfcf26c72e.png)

**Comment by Feat-FeAR** [comment]
If it helps, I got the following list of (maybe false) orphans:
```
[FeAR@SkyLake2 ~]$ pacman -Qdt
autoconf-archive 1:2022.09.03-1
base 3-2
cython 0.29.33-1
db 6.2.32-1
doxygen 1.9.6-1
manjaro-release 22.1.0-1
python-appdirs 1.4.4-7
python-pyparsing 3.0.9-1

[FeAR@SkyLake2 ~]$ sudo pacman -Rs $(pacman -Qdtq)
checking dependencies...
:: ldns optionally requires libpcap: ldns-dpa tool

Packages (27) argon2-20190702-4  cryptsetup-2.6.1-3.1  device-mapper-2.03.20-1  iproute2-6.2.0-2  iptables-1:1.8.9-1
              iputils-20221126-1  kbd-2.5.1-1  libbpf-1.1.0-1  libmnl-1.0.5-1  libnetfilter_conntrack-1.0.9-1
              libnfnetlink-1.0.2-1  libnftnl-1.2.5-1  libnl-3.7.0-3  libpcap-1.10.3-1  licenses-20220125-2
              lsb-release-2.0.r48.3cf5103-1  popt-1.19-1  systemd-252.9-1  systemd-sysvcompat-252.9-1
              autoconf-archive-1:2022.09.03-1  base-3-2  cython-0.29.33-1  db-6.2.32-1  doxygen-1.9.6-1
              manjaro-release-22.1.0-1  python-appdirs-1.4.4-7  python-pyparsing-3.0.9-1

Total Removed Size:  80.86 MiB

:: Do you want to remove these packages? [Y/n]
```

**Comment by sileshn** [comment]
Your issue is probably because you removed systemd files.
