### ISSUE TITLE
fails to update. Also cannot install pamac in the readme. PGP signature is incorrect. 

### ISSUE THREAD

**Issue by pyrofolium** [sileshn/ManjaroWSL2#7]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22621.1702]

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Repro Steps

sudo pacman -Syu

### Expected Behavior

Installs and updates. 

### Actual Behavior

[brian@DESKTOP-HMN4M4C ~]$ sudo pacman -Syu
error: wslutilities: signature from "WSL Utilities Package Signing Key <contact@wslutiliti.es>" is unknown trust
:: Synchronizing package databases...
 core                                               143.6 KiB  49.4 KiB/s 00:03 [##############################################] 100% extra                                             1636.8 KiB  2.13 MiB/s 00:01 [##############################################] 100% community                                            7.0 MiB  8.24 MiB/s 00:01 [##############################################] 100% multilib                                           145.5 KiB   808 KiB/s 00:00 [##############################################] 100% wslutilities                                      1153.0   B  1098   B/s 00:01 [##############################################] 100%error: wslutilities: key "2D4C887EB08424F157151C493DD50AA7E055D853" is unknown
:: Import PGP key 2D4C887EB08424F157151C493DD50AA7E055D853? [Y/n] Y
error: key "2D4C887EB08424F157151C493DD50AA7E055D853" could not be looked up remotely
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))

**Comment by sileshn** [comment]
This issue has already been discussed [here](https://github.com/sileshn/ManjaroWSL2/issues/6) and I have mentioned how to solve it. Please check if a issue has already been reported before reporting a new one. This is wslu's issue, not ManjaroWSL2's.

I won't be updating pamac from my side. I have provided how to add support. Its up to the user if he wants to use it.

**Comment by amad3us47** [comment]
sudo pacman-key -d A2861ABFD897DD37
wget https://pkg.wslutiliti.es/public.key
sudo pacman-key --add public.key

add the unknown showing key  in terminal to    pacman-key --lsign-key "unknown key"

then run :  
 sudo pacman -S archlinux-keyring
 sudo pacman -Syyu
